name: Check Out Demo
on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Before Checkout
        run: ls -la

      - name: cheeckout repository
        uses: actions/checkout@v4

      - name: After Checkout
        run: ls-la
