name: Exploar GitHub Runner
on:
  push:

jobs:
  exploar-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Print Current Directory
        run: pwd

      - name: Current User
        run: whoami

      - name: Hostname
        run: hostname

      - name: Linux Version
        run: uname -a

      - name: List name
        run: ls -la

      - name: Disk name
        run: df -h

      - name: Memory Information
        run: free -h
